name: Healthcheck Monitor
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check service
        id: healthcheck
        continue-on-error: true
        run: |
          if curl -s -f "http://ваш-сервис/healthcheck"; then
            echo "✅ Сервис работает"
            echo "status=ok" >> $GITHUB_OUTPUT
          else
            echo "status=down" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Send Telegram alert
        if: steps.healthcheck.outputs.status == 'down'
        run: |
          curl -s -X POST \
            "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_GROUP_CHAT_ID }}" \
            -d "text=🚨 Сервис упал! Проверьте: http://ваш-сервис/healthcheck"